version: "3.8"
services:
  postgresql:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: HerbowoputroIT2001
      POSTGRES_DB: saloradatabase
      POSTGRES_USER: prambudi
    volumes:
      - ./data:/var/lib/postgresql/data
  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
            - PGADMIN_DEFAULT_EMAIL=prambudi150@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=HerbowoputroIT2001
    ports:
        - "5050:80"
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
  salora-service-backend-dev:
    container_name: salora-service-backend-dev
    image: salora-service-backend-develop:0.0.1
    build: ./
    ports:
      - '8080:8080'
    depends_on:
      - postgresql
      - pgadmin
      - redis